spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wangqile
    url: jdbc:mysql://localhost:3306/bbs?useSSL=false
  jpa:
    show-sql: true
logging:
  level:
    cn.edu.ncu.bootjpademo: debug